<?php

declare(strict_types=1); ?>
</div> <!-- End .l-main-content -->

<footer class="l-footer">
    <div class="l-footer__info-box">
        <div class="l-footer__text">
            <p>Twokinds Admin-Panel</p>
            <p>Programmierung:
                <a href="https://github.com/RaptorXilef" target="_blank" rel="noopener noreferrer">Felix Maywald</a></p>
            <div class="website-version">v<?php echo \htmlspecialchars($settings['app_version'] ?? 'x'); ?> | <a href="<?php echo $baseUrl ?? ''; ?>/" target="_blank">Zur Webseite</a></div>
        </div>
    </div>

    <div class="l-footer__characters">
        <!-- Das dynamische Footer-Gimmick (Crowd) -->
        <div class="l-footer__characters-inner">
            <a href="<?php echo $baseUrl ?? ''; ?>/charaktere/char_0016" title="Karen"><img src="<?php echo $baseUrl ?? ''; ?>/assets/images/theme/footer-chars/karen.webp" alt="Karen"></a>
            <a href="<?php echo $baseUrl ?? ''; ?>/charaktere/char_0017" title="Maren"><img src="<?php echo $baseUrl ?? ''; ?>/assets/images/theme/footer-chars/maren.webp" alt="Maren"></a>
            <a href="<?php echo $baseUrl ?? ''; ?>/charaktere/char_0009" title="Raine"><img src="<?php echo $baseUrl ?? ''; ?>/assets/images/theme/footer-chars/raine.webp" alt="Raine"></a>
            <a href="<?php echo $baseUrl ?? ''; ?>/charaktere/char_0007" title="Sythe"><img src="<?php echo $baseUrl ?? ''; ?>/assets/images/theme/footer-chars/sythe.webp" alt="Sythe"></a>
            <a href="<?php echo $baseUrl ?? ''; ?>/charaktere/char_0018" title="Red"><img src="<?php echo $baseUrl ?? ''; ?>/assets/images/theme/footer-chars/red.webp" alt="Red"></a>
            <a href="<?php echo $baseUrl ?? ''; ?>/charaktere/char_0011" title="Kathrin"><img src="<?php echo $baseUrl ?? ''; ?>/assets/images/theme/footer-chars/kathrin.webp" alt="Kathrin"></a>
            <a href="<?php echo $baseUrl ?? ''; ?>/charaktere/char_0001" title="Trace"><img src="<?php echo $baseUrl ?? ''; ?>/assets/images/theme/footer-chars/trace.webp" alt="Trace"></a>
            <a href="<?php echo $baseUrl ?? ''; ?>/charaktere/char_0003" title="Flora"><img src="<?php echo $baseUrl ?? ''; ?>/assets/images/theme/footer-chars/flora.webp" alt="Flora"></a>
            <a href="<?php echo $baseUrl ?? ''; ?>/charaktere/char_0005" title="Natani"><img src="<?php echo $baseUrl ?? ''; ?>/assets/images/theme/footer-chars/natani.webp" alt="Natani"></a>
            <a href="<?php echo $baseUrl ?? ''; ?>/charaktere/char_0004" title="Keith"><img src="<?php echo $baseUrl ?? ''; ?>/assets/images/theme/footer-chars/keith.webp" alt="Keith"></a>
            <a href="<?php echo $baseUrl ?? ''; ?>/charaktere/char_0006" title="Zen"><img src="<?php echo $baseUrl ?? ''; ?>/assets/images/theme/footer-chars/zen.webp" alt="Zen"></a>
            <a href="<?php echo $baseUrl ?? ''; ?>/charaktere/char_0010" title="Eric"><img src="<?php echo $baseUrl ?? ''; ?>/assets/images/theme/footer-chars/eric.webp" alt="Eric"></a>
            <a href="<?php echo $baseUrl ?? ''; ?>/charaktere/char_0012" title="Mike"><img src="<?php echo $baseUrl ?? ''; ?>/assets/images/theme/footer-chars/mike.webp" alt="Mike"></a>
            <a href="<?php echo $baseUrl ?? ''; ?>/charaktere/char_0014" title="Evals"><img src="<?php echo $baseUrl ?? ''; ?>/assets/images/theme/footer-chars/evals.webp" alt="Evals"></a>
            <a href="<?php echo $baseUrl ?? ''; ?>/charaktere/char_0047" title="Lynn"><img src="<?php echo $baseUrl ?? ''; ?>/assets/images/theme/footer-chars/lynn.webp" alt="Lynn"></a>
            <a href="<?php echo $baseUrl ?? ''; ?>/charaktere/char_0015" title="Madelyn"><img src="<?php echo $baseUrl ?? ''; ?>/assets/images/theme/footer-chars/madelyn.webp" alt="Madelyn"></a>
        </div>
    </div>
</footer>
</div> <!-- End .l-page-wrapper -->
