<?php

declare(strict_types=1); ?>
</div> <!-- Schließt .content -->
</div> <!-- Schließt .content-area -->

<footer>
    <div class="bottom">
        <div class="bottom-left"></div>
        <div class="bottom-ctr">
            <p>Twokinds Admin-Panel</p>
            <p>Programmierung:
                <a href="https://github.com/RaptorXilef" target="_blank" rel="noopener noreferrer">Felix Maywald</a></p>
            <div class="website-version">v<?php echo \htmlspecialchars($settings['app_version'] ?? 'x'); ?> | <a href="<?php echo $baseUrl ?? ''; ?>/" target="_blank">Zur Webseite</a></div>
        </div>
        <div class="bottom-right"></div>
    </div>
    <div class="footer-img">
            <div class="footer-click-map">
                <a href="<?php echo $baseUrl ?? ''; ?>/charaktere/char_0016" aria-label="Charakter ansehen"></a>
                <a href="<?php echo $baseUrl ?? ''; ?>/charaktere/char_0017" aria-label="Charakter ansehen"></a>
                <a href="<?php echo $baseUrl ?? ''; ?>/charaktere/char_0009" aria-label="Charakter ansehen"></a>
                <a href="<?php echo $baseUrl ?? ''; ?>/charaktere/char_0007" aria-label="Charakter ansehen"></a>
                <a href="<?php echo $baseUrl ?? ''; ?>/charaktere/char_0018" aria-label="Charakter ansehen"></a>
                <a href="<?php echo $baseUrl ?? ''; ?>/charaktere/char_0011" aria-label="Charakter ansehen"></a>
                <a href="<?php echo $baseUrl ?? ''; ?>/charaktere/char_0001" aria-label="Charakter ansehen"></a>
                <a href="<?php echo $baseUrl ?? ''; ?>/charaktere/char_0003" aria-label="Charakter ansehen"></a>
                <a href="<?php echo $baseUrl ?? ''; ?>/charaktere/char_0005" aria-label="Charakter ansehen"></a>
                <a href="<?php echo $baseUrl ?? ''; ?>/charaktere/char_0004" aria-label="Charakter ansehen"></a>
                <a href="<?php echo $baseUrl ?? ''; ?>/charaktere/char_0006" aria-label="Charakter ansehen"></a>
                <a href="<?php echo $baseUrl ?? ''; ?>/charaktere/char_0010" aria-label="Charakter ansehen"></a>
                <a href="<?php echo $baseUrl ?? ''; ?>/charaktere/char_0012" aria-label="Charakter ansehen"></a>
                <a href="<?php echo $baseUrl ?? ''; ?>/charaktere/char_0014" aria-label="Charakter ansehen"></a>
                <a href="<?php echo $baseUrl ?? ''; ?>/charaktere/char_0047" aria-label="Charakter ansehen"></a>
                <a href="<?php echo $baseUrl ?? ''; ?>/charaktere/char_0015" aria-label="Charakter ansehen"></a>
            </div>
        </div>
    </footer>
</div> <!-- Schließt .main-container -->
</footer>
</div> <!-- Schließt .main-container -->
