ALTER TABLE `characters` ADD COLUMN `hair_color` VARCHAR(255) DEFAULT NULL;
ALTER TABLE `characters` ADD COLUMN `eye_color` VARCHAR(255) DEFAULT NULL;
ALTER TABLE `characters` ADD COLUMN `fur_color` VARCHAR(255) DEFAULT NULL;
