ALTER TABLE `characters` ADD COLUMN IF NOT EXISTS `hair_color` VARCHAR(255) DEFAULT NULL AFTER `languages`;
ALTER TABLE `characters` ADD COLUMN IF NOT EXISTS `eye_color` VARCHAR(255) DEFAULT NULL AFTER `hair_color`;
ALTER TABLE `characters` ADD COLUMN IF NOT EXISTS `fur_color` VARCHAR(255) DEFAULT NULL AFTER `eye_color`;
