<?php
/**
 * @file      ROOT/config/config_FILENAME_path.php
 * @package   twokinds.4lima.de
 * @author    Felix M. (@RaptorXilef)
 * @copyright 2025 Felix M.
 * @license   Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International <https://github.com/RaptorXilef/twokinds.4lima.de/blob/main/LICENSE>
 * @link      https://github.com/RaptorXilef/twokinds.4lima.de
 * @version   2.0.0
 * @since     1.0.0 Initiale Erstellung
 * @since     1.0.2 Konstanten für wichtige Dateien hinzugefügt.
 * @since     1.0.3 Pfade für comic_navigation.php hinzugefügt.
 * @since     1.0.4 Dateipfade robuster gestaltet: realpath() entfernt und DIRECTORY_SEPARATOR zur plattformunabhängigen String-Verkettung genutzt.
 * @since     2.0.0 Konstanten für relative Pfade von URL ausgehend hinzugefügt.
 */

// Die Konstanten basieren auf den Pfaden aus config_folder_path.php, 
// die keinen abschließenden Separator enthalten.

// DATA Pfade
define('VERSION_JSON_FILENAME', 'version.json');
define('VERSION_JSON_FILE', DIRECTORY_PRIVATE_DATA . DIRECTORY_SEPARATOR . VERSION_JSON_FILENAME);

define('ARCHIVE_CHAPTERS_JSON_FILENAME', 'archive_chapters.json');
define('ARCHIVE_CHAPTERS_JSON_FILE', DIRECTORY_PRIVATE_DATA . DIRECTORY_SEPARATOR . ARCHIVE_CHAPTERS_JSON_FILENAME);

define('CHARAKTERE_JSON_FILENAME', 'charaktere.json');
define('CHARAKTERE_JSON_FILE', DIRECTORY_PRIVATE_DATA . DIRECTORY_SEPARATOR . CHARAKTERE_JSON_FILENAME);

define('COMIC_VAR_JSON_FILENAME', 'comic_var.json');
define('COMIC_VAR_JSON_FILE', DIRECTORY_PRIVATE_DATA . DIRECTORY_SEPARATOR . COMIC_VAR_JSON_FILENAME);

define('SITEMAP_JSON_FILENAME', 'sitemap.json');
define('SITEMAP_JSON_FILE', DIRECTORY_PRIVATE_DATA . DIRECTORY_SEPARATOR . SITEMAP_JSON_FILENAME);


// DATA CHACHE Pfade
// (Cache-Dateien, die automatisch von der Anwendung erstellt und verwaltet werden)
define('COMIC_IMAGE_CACHE_JSON_FILENAME', 'comic_image_cache.json');
define('COMIC_IMAGE_CACHE_JSON_FILE', DIRECTORY_PRIVATE_CACHE . DIRECTORY_SEPARATOR . COMIC_IMAGE_CACHE_JSON_FILENAME);


// CONFIG Pfade
define('CONFIG_MAIN_PHP_FILENAME', 'config_main.php');
define('CONFIG_MAIN_PHP_FILE', DIRECTORY_PRIVATE_CONFIG . DIRECTORY_SEPARATOR . CONFIG_MAIN_PHP_FILENAME);

define('CONFIG_FOLDER_PATH_PHP_FILENAME', 'config_folder_path.php');
define('CONFIG_FOLDER_PATH_PHP_FILE', DIRECTORY_PRIVATE_CONFIG . DIRECTORY_SEPARATOR . CONFIG_FOLDER_PATH_PHP_FILENAME);

define('CONFIG_FILENAME_PATH_PHP_FILENAME', 'config_FILENAME_path.php');
define('CONFIG_FILENAME_PATH_PHP_FILE', DIRECTORY_PRIVATE_CONFIG . DIRECTORY_SEPARATOR . CONFIG_FILENAME_PATH_PHP_FILENAME);

define('CONFIG_GENERATOR_SETTINGS_JSON_FILENAME', 'config_generator_settings.json');
define('CONFIG_GENERATOR_SETTINGS_JSON_FILE', DIRECTORY_PRIVATE_CONFIG . DIRECTORY_SEPARATOR . CONFIG_GENERATOR_SETTINGS_JSON_FILENAME);

define('CONFIG_RSS_CONFIG_JSON_FILENAME', 'config_rss.json');
define('CONFIG_RSS_CONFIG_JSON_FILE', DIRECTORY_PRIVATE_CONFIG . DIRECTORY_SEPARATOR . CONFIG_RSS_CONFIG_JSON_FILENAME);


// SECRETS Pfade
define('SECRET_ADMIN_USERS_JSON_FILENAME', 'admin_users.json');
define('SECRET_ADMIN_USERS_JSON_FILE', DIRECTORY_PRIVATE_SECRETS . DIRECTORY_SEPARATOR . SECRET_ADMIN_USERS_JSON_FILENAME);

define('SECRET_LOGIN_ATTEMPTS_JSON_FILENAME', 'login_attempts.json');
define('SECRET_LOGIN_ATTEMPTS_JSON_FILE', DIRECTORY_PRIVATE_SECRETS . DIRECTORY_SEPARATOR . SECRET_LOGIN_ATTEMPTS_JSON_FILENAME);


// TEMPLATES Pfade
define('TEMPLATE_HEADER_FILENAME', 'header.php');
define('TEMPLATE_HEADER_FILE', DIRECTORY_PRIVATE_PARTIAL_TEMLATES . DIRECTORY_SEPARATOR . TEMPLATE_HEADER_FILENAME);

define('TEMPLATE_FOOTER_FILENAME', 'footer.php');
define('TEMPLATE_FOOTER_FILE', DIRECTORY_PRIVATE_PARTIAL_TEMLATES . DIRECTORY_SEPARATOR . TEMPLATE_FOOTER_FILENAME);


// COMPONENTS Pfade
define('MENU_FILENAME', 'public_menue_config.php');
define('MENU_FILE', DIRECTORY_PUBLIC_COMPONENTS . DIRECTORY_SEPARATOR . MENU_FILENAME);

define('CACHE_CONFIG_FILENAME', 'cache_config.php');
define('CACHE_CONFIG_FILE', DIRECTORY_PUBLIC_COMPONENTS . DIRECTORY_SEPARATOR . CACHE_CONFIG_FILENAME);

define('CHARAKTERE_DISPLAY_FILENAME', 'character_display.php');
define('CHARAKTERE_DISPLAY_FILE', DIRECTORY_PUBLIC_COMPONENTS . DIRECTORY_SEPARATOR . CHARAKTERE_DISPLAY_FILENAME);

define('CHARACTER_IMAGE_HELPER_FILENAME', 'character_image_helper.php');
define('CHARACTER_IMAGE_HELPER_FILE', DIRECTORY_PUBLIC_COMPONENTS . DIRECTORY_SEPARATOR . CHARACTER_IMAGE_HELPER_FILENAME);

define('CHARACTER_PAGE_RENDERER_FILENAME', 'character_page_renderer.php');
define('CHARACTER_PAGE_RENDERER_FILE', DIRECTORY_PUBLIC_COMPONENTS . DIRECTORY_SEPARATOR . CHARACTER_PAGE_RENDERER_FILENAME);

define('COMIC_PAGE_RENDERER_FILENAME', 'comic_page_renderer.php');
define('COMIC_PAGE_RENDERER_FILE', DIRECTORY_PUBLIC_COMPONENTS . DIRECTORY_SEPARATOR . COMIC_PAGE_RENDERER_FILENAME);

define('GET_COMIC_IMAGE_PATH_FILENAME', 'get_comic_image_path');
define('GET_COMIC_IMAGE_PATH_FILE', DIRECTORY_PUBLIC_COMPONENTS . DIRECTORY_SEPARATOR . GET_COMIC_IMAGE_PATH_FILENAME);

define('IMAGE_CACHE_HELPER_FILENAME', 'image_cache_helper.php');
define('IMAGE_CACHE_HELPER_FILE', DIRECTORY_PUBLIC_COMPONENTS . DIRECTORY_SEPARATOR . IMAGE_CACHE_HELPER_FILENAME);

define('LOAD_COMIC_DATA_FILENAME', 'load_comic_data.php');
define('LOAD_COMIC_DATA_FILE', DIRECTORY_PUBLIC_COMPONENTS . DIRECTORY_SEPARATOR . LOAD_COMIC_DATA_FILENAME);

define('NAV_LINK_HELPER_FILENAME', 'nav_link_helper.php');
define('NAV_LINK_HELPER_FILE', DIRECTORY_PUBLIC_COMPONENTS . DIRECTORY_SEPARATOR . NAV_LINK_HELPER_FILENAME);

define('COMIC_NAVIGATION_FILENAME', 'comic_navigation.php');
define('COMIC_NAVIGATION_FILE', DIRECTORY_PUBLIC_ASSETS . DIRECTORY_SEPARATOR . COMIC_NAVIGATION_FILENAME);


/// ADMIN COMPONENTS Pfade
define('ADMIN_MENU_FILENAME', 'admin_menue_config.php');
define('ADMIN_MENU_FILE', DIRECTORY_PUBLIC_ADMIN_COMPONENTS . DIRECTORY_SEPARATOR . ADMIN_MENU_FILENAME);

define('ADMIN_MENU_LOGIN_FILENAME', 'admin_menue_config_login.php');
define('ADMIN_MENU_LOGIN_FILE', DIRECTORY_PUBLIC_ADMIN_COMPONENTS . DIRECTORY_SEPARATOR . ADMIN_MENU_LOGIN_FILENAME);

define('ADMIN_KEEP_ALIVE_FILENAME', 'keep_alive.php');
define('ADMIN_KEEP_ALIVE_FILE', DIRECTORY_PUBLIC_ADMIN_COMPONENTS . DIRECTORY_SEPARATOR . ADMIN_KEEP_ALIVE_FILENAME);

define('ADMIN_SESSION_TIMEOUT_MODAL_FILENAME', 'session_timeout_modal.php');
define('ADMIN_SESSION_TIMEOUT_MODAL_FILE', DIRECTORY_PUBLIC_ADMIN_COMPONENTS . DIRECTORY_SEPARATOR . ADMIN_SESSION_TIMEOUT_MODAL_FILENAME);


/// NEU
define('PUBLIC_INIT_FILENAME', 'public_init.php');
define('PUBLIC_INIT_FILE', DIRECTORY_PRIVATE_COMPONENTS . DIRECTORY_SEPARATOR . PUBLIC_INIT_FILENAME);

define('ADMIN_INIT_FILENAME', 'admin_init.php');
define('ADMIN_INIT_FILE', DIRECTORY_PRIVATE_COMPONENTS . DIRECTORY_SEPARATOR . ADMIN_INIT_FILENAME);


// ##################################################################
// --- CSS/JS Pfade ---
// (absolute Pfade vom ROOT-Pfad ausgehend, z.B. für <link> oder <script>)
// ##################################################################

// CSS
define('CHARAKTERE_DISPLAY_MIN_CSS_FILENAME', 'character_display.min.css');
define('CHARAKTERE_DISPLAY_MIN_CSS_FILE', DIRECTORY_PUBLIC_CSS . DIRECTORY_SEPARATOR . CHARAKTERE_DISPLAY_MIN_CSS_FILENAME);

define('CHARAKTERE_PAGE_MIN_CSS_FILENAME', 'character_page.min.css');
define('CHARAKTERE_PAGE_MIN_CSS_FILE', DIRECTORY_PUBLIC_CSS . DIRECTORY_SEPARATOR . CHARAKTERE_PAGE_MIN_CSS_FILENAME);

define('COOKIE_BANNER_MIN_CSS_FILENAME', 'cookie_banner.min.css');
define('COOKIE_BANNER_MIN_CSS_FILE', DIRECTORY_PUBLIC_CSS . DIRECTORY_SEPARATOR . COOKIE_BANNER_MIN_CSS_FILENAME);

define('COOKIE_BANNER_DARK_MIN_CSS_FILENAME', 'cookie_banner_dark.min.css');
define('COOKIE_BANNER_DARK_MIN_CSS_FILE', DIRECTORY_PUBLIC_CSS . DIRECTORY_SEPARATOR . COOKIE_BANNER_DARK_MIN_CSS_FILENAME);

define('MAIN_MIN_CSS_FILENAME', 'main.min.css');
define('MAIN_MIN_CSS_FILE', DIRECTORY_PUBLIC_CSS . DIRECTORY_SEPARATOR . MAIN_MIN_CSS_FILENAME);

define('MAIN_DARK_MIN_CSS_FILENAME', 'main.min.css');
define('MAIN_DARK_MIN_CSS_FILE', DIRECTORY_PUBLIC_CSS . DIRECTORY_SEPARATOR . MAIN_DARK_MIN_CSS_FILENAME);


// JS
define('ARCHIVE_MIN_JS_FILENAME', 'archive.min.js');
define('ARCHIVE_MIN_JS_FILE', DIRECTORY_PUBLIC_JS . DIRECTORY_SEPARATOR . ARCHIVE_MIN_JS_FILENAME);

define('CHARAKTERE_MIN_JS_FILENAME', 'charaktere.min.js');
define('CHARAKTERE_MIN_JS_FILE', DIRECTORY_PUBLIC_JS . DIRECTORY_SEPARATOR . CHARAKTERE_MIN_JS_FILENAME);

define('COMIC_MIN_JS_FILENAME', 'comic.min.js');
define('COMIC_MIN_JS_FILE', DIRECTORY_PUBLIC_JS . DIRECTORY_SEPARATOR . COMIC_MIN_JS_FILENAME);

define('COMMON_MIN_JS_FILENAME', 'common.min.js');
define('COMMON_MIN_JS_FILE', DIRECTORY_PUBLIC_JS . DIRECTORY_SEPARATOR . COMMON_MIN_JS_FILENAME);

define('COOKIE_BANNER_MIN_JS_FILENAME', 'cookie_consent.min.js');
define('COOKIE_BANNER_MIN_JS_FILE', DIRECTORY_PUBLIC_JS . DIRECTORY_SEPARATOR . COOKIE_BANNER_MIN_JS_FILENAME);


// ADMIN JS
define('DATA_EDITOR_CHARAKTERE_MIN_JS_FILENAME', 'data_editor_charaktere.js');
define('DATA_EDITOR_CHARAKTERE_MIN_JS_FILE', DIRECTORY_PUBLIC_ADMIN_JS . DIRECTORY_SEPARATOR . DATA_EDITOR_CHARAKTERE_MIN_JS_FILENAME);

define('GENERATOR_RSS_MIN_JS_FILENAME', 'generator_rss.min.js');
define('GENERATOR_RSS_MIN_JS_FILE', DIRECTORY_PUBLIC_ADMIN_JS . DIRECTORY_SEPARATOR . GENERATOR_RSS_MIN_JS_FILENAME);

define('SESSION_TIMEOUT_MIN_JS_FILENAME', 'session_timeout.min.js');
define('SESSION_TIMEOUT_MIN_JS_FILE', DIRECTORY_PUBLIC_ADMIN_JS . DIRECTORY_SEPARATOR . SESSION_TIMEOUT_MIN_JS_FILENAME);


// ##################################################################
// --- CSS/JS URL-Pfade ---
// (absolute Pfade von der URL ausgehend, z.B. für <link> oder <script>)
// ##################################################################
// CSS
define('CHARAKTERE_DISPLAY_MIN_CSS_FILE_URL', DIRECTORY_PUBLIC_CSS_URL . DIRECTORY_SEPARATOR . CHARAKTERE_DISPLAY_MIN_CSS_FILENAME);
define('CHARAKTERE_PAGE_MIN_CSS_FILE_URL', DIRECTORY_PUBLIC_CSS_URL . DIRECTORY_SEPARATOR . CHARAKTERE_PAGE_MIN_CSS_FILENAME);
define('COOKIE_BANNER_MIN_CSS_FILE_URL', DIRECTORY_PUBLIC_CSS_URL . DIRECTORY_SEPARATOR . COOKIE_BANNER_MIN_CSS_FILENAME);
define('COOKIE_BANNER_DARK_MIN_CSS_FILE_URL', DIRECTORY_PUBLIC_CSS_URL . DIRECTORY_SEPARATOR . COOKIE_BANNER_DARK_MIN_CSS_FILENAME);
define('MAIN_MIN_CSS_FILE_URL', DIRECTORY_PUBLIC_CSS_URL . DIRECTORY_SEPARATOR . MAIN_MIN_CSS_FILENAME);
define('MAIN_DARK_MIN_CSS_FILE_URL', DIRECTORY_PUBLIC_CSS_URL . DIRECTORY_SEPARATOR . MAIN_DARK_MIN_CSS_FILENAME);

// JS
define('ARCHIVE_MIN_JS_FILE_URL', DIRECTORY_PUBLIC_JS_URL . DIRECTORY_SEPARATOR . ARCHIVE_MIN_JS_FILENAME);
define('CHARAKTERE_MIN_JS_FILE_URL', DIRECTORY_PUBLIC_JS_URL . DIRECTORY_SEPARATOR . CHARAKTERE_MIN_JS_FILENAME);
define('COMIC_MIN_JS_FILE_URL', DIRECTORY_PUBLIC_JS_URL . DIRECTORY_SEPARATOR . COMIC_MIN_JS_FILENAME);
define('COMMON_MIN_JS_FILE_URL', DIRECTORY_PUBLIC_JS_URL . DIRECTORY_SEPARATOR . COMMON_MIN_JS_FILENAME);
define('COOKIE_BANNER_MIN_JS_FILE_URL', DIRECTORY_PUBLIC_JS_URL . DIRECTORY_SEPARATOR . COOKIE_BANNER_MIN_JS_FILENAME);


// ADMIN JS
define('DATA_EDITOR_CHARAKTERE_MIN_JS_FILE_URL', DIRECTORY_PUBLIC_ADMIN_JS_URL . DIRECTORY_SEPARATOR . DATA_EDITOR_CHARAKTERE_MIN_JS_FILENAME);
define('GENERATOR_RSS_MIN_JS_FILE_URL', DIRECTORY_PUBLIC_ADMIN_JS_URL . DIRECTORY_SEPARATOR . GENERATOR_RSS_MIN_JS_FILENAME);
define('SESSION_TIMEOUT_MIN_JS_FILE_URL', DIRECTORY_PUBLIC_ADMIN_JS_URL . DIRECTORY_SEPARATOR . SESSION_TIMEOUT_MIN_JS_FILENAME);

?>