<!-- ======================================================================= -->
<!-- GALLERY MODAL -->
<!-- ======================================================================= -->
<div id="gallery-modal"
     class="modal z-1060">
    <div class="modal-overlay btn-close-gallery-modal"></div>
    <div class="modal-content modal-lg modal-flex">
        <div class="modal-header-wrapper">
            <h2 id="gallery-modal-title">Bild aus Galerie wählen</h2>
            <button class="modal-close btn-close-gallery-modal">&times;</button>
        </div>
        <div class="modal-scroll-content">
            <p class="text-light font-small mt-0 mb-15">Klicke auf Bilder, um sie zu markieren oder abzuwählen.
                Bestätige anschließend deine Auswahl.</p>
            <div class="char-selection-grid"
                 id="gallery-grid-dynamic"></div>
        </div>
        <div class="modal-footer-actions">
            <div class="modal-buttons">
                <button type="button"
                        class="button btn-close-gallery-modal">Abbrechen</button>
                <button type="button"
                        class="button add"
                        id="btn-gallery-confirm"><i class="fa-solid fa-check"></i> Auswahl übernehmen</button>
            </div>
        </div>
    </div>
</div>
