<!-- ======================================================================= -->
<!-- GALLERY MODAL -->
<!-- ======================================================================= -->
<div id="gallery-modal"
     class="modal"
     style="z-index: 1050;">
    <div class="modal-overlay btn-close-gallery-modal"></div>
    <div class="modal-content modal-lg">
        <div class="modal-header-wrapper">
            <h2 id="gallery-modal-title">Bild aus Galerie wählen</h2>
            <button class="modal-close btn-close-gallery-modal">&times;</button>
        </div>
        <div class="modal-scroll-content">
            <div class="char-selection-grid"
                 id="gallery-grid-dynamic"><!-- Wird per JS befüllt --></div>
        </div>
    </div>
</div>
