<?php

declare(strict_types=1);

use App\Core\Entity\Character;
use App\Core\Entity\CharacterGroup;
use App\Core\Entity\User;

/**
 * @var string           $baseUrl
 * @var Character[]      $characters
 * @var CharacterGroup[] $groups
 * @var string[]         $existingRanks
 * @var string[]         $existingChapters
 * @var string[]         $availableImages
 * @var array            $perms
 * @var User[]           $allUsers
 */
?>

<?php include __DIR__ . '/modals/_modal_comic.phtml'; ?>
<?php include __DIR__ . '/modals/_modal_character.phtml'; ?>
<?php include __DIR__ . '/modals/_modal_gallery.phtml'; ?>
<?php include __DIR__ . '/modals/_modal_chapter.phtml'; ?>
<?php include __DIR__ . '/modals/_modal_overwrite.phtml'; ?>
<?php include __DIR__ . '/modals/_overlay_image_hover.phtml'; ?>
<?php include __DIR__ . '/modals/_modal_report.phtml'; ?>
<?php include __DIR__ . '/modals/_modal_cropper.phtml'; ?>
<?php include __DIR__ . '/modals/_modal_mail_preview.phtml'; ?>
